main: me.hammerle.kp.KajetansPlugin
name: KajetansPlugin
version: "0.0.1"
api-version: "1.17"
author: AUTHOR
description: DESCRIPTION
commands:
  ex:
    description: Base command for EXAMPLE
    usage: "For a list of commands, type /ex help"
    aliases: example
permissions:
  example.test:
    description: DESCRIPTION
    default: true
  example.*:
    description: Grants all other permissions
    default: false
    children:
      example.test: true